### ISSUE TITLE
Authentica yourself at bot.

### ISSUE THREAD

**Issue by DanielSiepmann** [super3/IRC-Bot#13]
Currently everyone can run all commands.

Make certain commands available only for authed users.

Therefore we have to built in an auth mechanism and a command that allows users to auth.

**Comment by Yoshi2889** [comment]
I wrote a solution using hostnames here:
Will publish a PR (amongst others) later.

**Comment by Yoshi2889** [comment]
Think this is fixed with the hostname authentication, or do you want more auth methods?
