### ISSUE TITLE
how to only log chat not login info etc..

### ISSUE THREAD

**Issue by boelle** [super3/IRC-Bot#68]
so i got it running like i want.... thou i discovered a nasty thing... it puts everything in the log including passwords to freenode etc...

so is there a settings that starts the log after i am in the channel and only log what people write in the open?

**Comment by Yoshi2889** [comment]
Working on this.

**Comment by Yoshi2889** [comment]
Should be fixed with PR #69, please edit your config with the appropriate channel.
